// Generated by npm run bindings. Do not edit.
export type ErrorCode = "invalid_input" | "not_found" | "invalid_executable" | "probe_failed" | "timeout" | "spawn_failed" | "process_failed" | "capacity" | "settings" | "settings_version" | "not_configured" | "auth_denied" | "auth_expired" | "auth_invalid" | "auth_provider" | "network" | "unauthenticated" | "unauthorized" | "rate_limited" | "invalid_response" | "twitch_server" | "cancelled" | "credential_store" | "internal";
export type AppError = { code: ErrorCode, message: string, };
export type ProbeRequest = { customPath: string | null, };
export type LaunchRequest = { url: string, quality: string, };
export type StopRequest = { sessionId: string, };
export type Settings = { version: number, streamlinkPath: string | null, };
export type BackendDiagnostics = { name: string, version: string, platform: string, settingsPath: string, settings: Settings, authConfigured: boolean, };
export type ProbeResult = { executable: string, version: string, };
export type SessionPhase = "running" | "stopping" | "exited" | "failed";
export type LogSource = "stdout" | "stderr" | "supervisor";
export type LogEntry = { sequence: number, source: LogSource, text: string, };
export type SessionSnapshot = { id: string, phase: SessionPhase, pid: number, url: string, quality: string, exitCode: number | null, stopRequested: boolean, logs: Array<LogEntry>, droppedLogEntries: number, };
export type AuthPhase = "not_configured" | "restoring" | "signed_out" | "authorizing" | "authenticated" | "cancelled" | "expired" | "error";
export type DeviceAuthorization = { userCode: string, verificationUri: string, expiresIn: number, };
export type AuthUser = { id: string, login: string, scopes: Array<string>, expiresIn: number, };
export type AuthStatus = { phase: AuthPhase, user: AuthUser | null, authorization: DeviceAuthorization | null, error: AppError | null, credentialStorage: string, };
export type Account = { id: string, login: string, displayName: string, profileImageUrl: string | null, };
