use serde::{Deserialize, Serialize};
use ts_rs::TS;

pub mod services;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    InvalidInput,
    StreamlinkNotFound,
    UnsupportedStreamlink,
    PlayerNotFound,
    InvalidPlayer,
    StartupFailed,
    StreamlinkExited,
    RestartFailed,
    StreamOffline,
    NotFound,
    InvalidExecutable,
    ProbeFailed,
    Timeout,
    SpawnFailed,
    ProcessFailed,
    Capacity,
    Settings,
    SettingsVersion,
    NotConfigured,
    AuthDenied,
    AuthExpired,
    AuthInvalid,
    AuthProvider,
    Network,
    Unauthenticated,
    Unauthorized,
    RateLimited,
    InvalidResponse,
    TwitchServer,
    Cancelled,
    CredentialStore,
    Internal,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AppError {
    pub code: ErrorCode,
    pub message: String,
}

impl AppError {
    pub fn new(code: ErrorCode, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }
}

impl std::fmt::Display for AppError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for AppError {}

pub type Result<T> = std::result::Result<T, AppError>;

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProbeRequest {
    pub custom_path: Option<String>,
}

#[cfg(any(test, feature = "test-support"))]
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LaunchRequest {
    pub url: String,
    pub quality: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct StopRequest {
    pub session_id: String,
}

/// DTO definitions come from Rust; the deliberately small command map is reviewed
/// alongside commands/mod.rs. Tokens deliberately do not implement TS/Serialize.
pub fn typescript_bindings() -> String {
    use crate::helix::browse::*;
    use crate::streamlink::{discovery::PlayerDiscovery, playback::*};
    use crate::{config::Settings, diagnostics::BackendDiagnostics, streamlink::*, twitch::*};
    let declarations = [
        ErrorCode::decl(),
        QualityPolicy::decl(),
        PlayerMode::decl(),
        PlayerSettings::decl(),
        PlaybackRequest::decl(),
        RestartRequest::decl(),
        PlaybackStream::decl(),
        PlayerDiscovery::decl(),
        BrowseRequest::decl(),
        EntityRequest::decl(),
        SearchRequest::decl(),
        DataFreshness::decl(),
        LiveState::decl(),
        StreamSummary::decl(),
        CategorySummary::decl(),
        ChannelSummary::decl(),
        PagedResult::<StreamSummary>::decl(),
        ChannelDetails::decl(),
        CategoryDetails::decl(),
        AppError::decl(),
        ProbeRequest::decl(),
        StopRequest::decl(),
        Settings::decl(),
        BackendDiagnostics::decl(),
        ProbeResult::decl(),
        SessionPhase::decl(),
        LogSource::decl(),
        LogEntry::decl(),
        SessionSnapshot::decl(),
        AuthPhase::decl(),
        DeviceAuthorization::decl(),
        AuthUser::decl(),
        AuthStatus::decl(),
        crate::helix::models::Account::decl(),
    ];
    format!(
        "// Generated by npm run bindings. Do not edit.\n{}\n",
        declarations
            .iter()
            .map(|s| format!("export {s}"))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn frontend_dtos_match_rust() {
        assert_eq!(
            super::typescript_bindings(),
            include_str!("../../../src/lib/generated.ts"),
            "Run npm run bindings after changing DTOs"
        );
    }
}
