use serde::{Deserialize, Serialize};
use ts_rs::{Config, TS};

pub mod background;
pub mod chat;
pub mod services;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    InvalidInput,
    Incomplete,
    Notification,
    BrowserOpen,
    StreamlinkNotFound,
    UnsupportedStreamlink,
    PlayerNotFound,
    InvalidPlayer,
    StartupFailed,
    StreamlinkExited,
    RestartFailed,
    StreamOffline,
    NotFound,
    InvalidExecutable,
    ProbeFailed,
    Timeout,
    SpawnFailed,
    ProcessFailed,
    Capacity,
    Settings,
    SettingsVersion,
    NotConfigured,
    AuthDenied,
    AuthExpired,
    AuthInvalid,
    AuthProvider,
    Network,
    Unauthenticated,
    Unauthorized,
    RateLimited,
    InvalidResponse,
    TwitchServer,
    Cancelled,
    CredentialStore,
    Internal,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct AppError {
    pub code: ErrorCode,
    pub message: String,
}

impl AppError {
    pub fn new(code: ErrorCode, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }
}

impl std::fmt::Display for AppError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for AppError {}

pub type Result<T> = std::result::Result<T, AppError>;

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProbeRequest {
    pub custom_path: Option<String>,
}

#[cfg(any(test, feature = "test-support"))]
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct LaunchRequest {
    pub url: String,
    pub quality: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct StopRequest {
    pub session_id: String,
}

/// DTO definitions come from Rust; the deliberately small command map is reviewed
/// alongside commands/mod.rs. Tokens deliberately do not implement TS/Serialize.
pub fn typescript_bindings() -> String {
    use crate::helix::browse::*;
    use crate::streamlink::{discovery::PlayerDiscovery, playback::*};
    use crate::{config::*, diagnostics::BackendDiagnostics, streamlink::*, twitch::*};
    let config = Config::default();
    let declarations = [
        ErrorCode::decl(&config),
        background::NotificationPermission::decl(&config),
        background::NotificationTestAction::decl(&config),
        background::DesktopAction::decl(&config),
        background::DesktopStatus::decl(&config),
        background::AcknowledgeDesktopAction::decl(&config),
        chat::ChatRequest::decl(&config),
        QualityPolicy::decl(&config),
        PlayerMode::decl(&config),
        PlayerSettings::decl(&config),
        PlaybackRequest::decl(&config),
        RestartRequest::decl(&config),
        PlaybackStream::decl(&config),
        PlayerDiscovery::decl(&config),
        BrowseRequest::decl(&config),
        StreamBrowseRequest::decl(&config),
        CategoryStreamsRequest::decl(&config),
        EntityRequest::decl(&config),
        LookupChannelRequest::decl(&config),
        ChannelIdentity::decl(&config),
        SearchRequest::decl(&config),
        DataFreshness::decl(&config),
        LiveState::decl(&config),
        StreamSummary::decl(&config),
        CategorySummary::decl(&config),
        ChannelSummary::decl(&config),
        PagedResult::<StreamSummary>::decl(&config),
        ChannelDetails::decl(&config),
        CategoryDetails::decl(&config),
        AppError::decl(&config),
        ProbeRequest::decl(&config),
        StopRequest::decl(&config),
        Settings::decl(&config),
        BackgroundSettings::decl(&config),
        crate::monitor::MonitorPhase::decl(&config),
        crate::monitor::MonitorStatus::decl(&config),
        Theme::decl(&config),
        TextScale::decl(&config),
        StreamLanguage::decl(&config),
        ChannelOverrides::decl(&config),
        ChannelSettingsRequest::decl(&config),
        SaveChannelSettingsRequest::decl(&config),
        ChannelSettings::decl(&config),
        EffectivePlaybackSettings::decl(&config),
        BackendDiagnostics::decl(&config),
        ProbeResult::decl(&config),
        SessionPhase::decl(&config),
        LogSource::decl(&config),
        LogEntry::decl(&config),
        SessionSnapshot::decl(&config),
        AuthPhase::decl(&config),
        DeviceAuthorization::decl(&config),
        AuthUser::decl(&config),
        AuthStatus::decl(&config),
        crate::helix::models::Account::decl(&config),
    ];
    format!(
        "// Generated by npm run bindings. Do not edit.\n{}\n",
        declarations
            .iter()
            .map(|s| format!("export {s}"))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn frontend_dtos_match_rust() {
        assert_eq!(
            super::typescript_bindings(),
            include_str!("../../../src/lib/generated.ts"),
            "Run npm run bindings after changing DTOs"
        );
    }
}
